mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView
from .views import root

urlpatterns = [
    path('', TemplateView.as_view(template_name='root.html'), name='root'),
    path('pricing/', include('pricing.urls')),
    path('admin/', admin.site.urls),
    path('calculate/', include('pricing_api.urls', namespace='pricing_api')),  # Use the namespace
]

mysite/pricing/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

mysite/pricing_api/urls.py
# pricing_api/urls.py
from django.urls import path
from .views import CalculatePricing

app_name = 'pricing_api'

urlpatterns = [
    path('calculate_pricing/', CalculatePricing.as_view(), name='calculate_pricing'),
]

mysite/pricing/models.py
from django.db import models
from django.contrib.auth.models import User

class PricingConfiguration(models.Model):
    param_name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='configurations_created')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='configurations_modified')
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.param_name

mysite/pricing/forms.py
from django import forms
from .models import PricingConfiguration

class PricingConfigurationForm(forms.ModelForm):
    class Meta:
        model = PricingConfiguration
        fields = ['param_name', 'is_active']

mysite/mysite/views.py
from django.shortcuts import render

def root(request):
    return render(request, 'root.html')

mysite/pricing/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the pricing index.")

mysite/pricing_api/views.py
# pricing_api/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from django.utils import timezone

class CalculatePricing(APIView):
    template_name = 'pricing_api/calculate_pricing.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        distance_travelled = float(request.data.get('distance_travelled', 0))
        total_time = float(request.data.get('total_time', 0))
        wait_time = float(request.data.get('wait_time', 0))

        current_date = timezone.now().date()
        day_of_week = current_date.weekday()

        dist_base_price = {} 
        ## base prices for all the days are set
        dist_base_price[1] = 80
        dist_base_price[2] = 80
        dist_base_price[3] = 80
        dist_base_price[0] = 90
        dist_base_price[4] = 90
        dist_base_price[5] = 85
        dist_base_price[6] = 85
        ## till three kms it uses the additional_price which is 28 per KM.
        ## TMF will be 1x under 1hr, 1.25x till 2 hrs, 2.2x till 3hrs and after that is 4x
        ## waiting charge is 5rs per min.
        distace_add_price = 28
        wait_charge = 5
        tmf = {}
        tmf[1] =1
        tmf[2] = 1.25
        tmf[3] = 2.2
        tmf[4] = 4
        price = 0
        tmf_factor = int((total_time-wait_time)/60 + 1)
        tmf_factor = min(tmf_factor, 4)
        if distance_travelled < 3:
            price = ((distance_travelled)*distace_add_price + (tmf[tmf_factor])*(total_time-wait_time) + (wait_time*wait_charge))
        else:
            price = (dist_base_price[day_of_week] + (distance_travelled-3)*distace_add_price + (tmf[tmf_factor])*(total_time-wait_time) + (wait_time*wait_charge))
        
        return render(request, self.template_name, {'price': price})

mysite/mysite/templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pricing_v2</title>
    <style>
        body {
            background-color: #333; 
            color: #fff; 
            font-family: Arial, sans-serif; 
            padding: 20px; 
            text-align: center; 
        }

        h1 {
            color: #ffd700; 
        }

        a {
            text-decoration: none; 
        }

        button {
            background-color: #555; 
            color: #fff; 
            padding: 10px 20px;
            margin: 10px;
            border: none; 
            cursor: pointer; 
            border-radius: 5px; 
        }

        button:hover {
            background-color: #777; 
        }
    </style>
</head>
<body>
    <h1>Welcome to Pricing_v2!</h1>
    <a href="{% url 'admin:login' %}"><button>Go to Admin Portal</button></a>
    <a href="{% url 'pricing_api:calculate_pricing' %}"><button>Calculate Price API</button></a>
</body>
</html>

mysite/pricing_api/templates/pricing_api/calculate_pricing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calculate Pricing</title>
    <style>
        body {
            background-color: #333; 
            color: #fff; 
            font-family: Arial, sans-serif;
        }

        h1, h2 {
            color: #ffc107;
        }

        form {
            max-width: 400px; 
            margin: 20px auto; 
            padding: 20px;
            background-color: #444; 
            border-radius: 10px; 
        }

        label {
            display: block;
            margin-bottom: 10px;
            color: #ffc107; 
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #666; 
            border-radius: 5px; 
            background-color: #555; 
            color: #fff; 
        }

        button {
            background-color: #ffc107; 
            color: #333; 
            padding: 10px 15px;
            border: none;
            border-radius: 5px; 
            cursor: pointer;
        }

        button:hover {
            background-color: #ffdb58; 
        }
    </style>
</head>
<body>
    <h1>Calculate Pricing</h1>

    <form method="post" action="{% url 'pricing_api:calculate_pricing' %}">
        {% csrf_token %}
        
        <label for="distance_travelled">Total Distance travelled:(in kms)</label>
        <input type="number" name="distance_travelled" step="0.1" required>
        
        <label for="total_time">Total time:(in mins)</label>
        <input type="number" name="total_time" required>
        
        <label for="wait_time">Wait Time:(in min)</label>
        <input type="number" name="wait_time" required>

        <button type="submit">Calculate</button>
    </form>

    {% if price %}
        <h2>Calculated Price: {{ price }}</h2>
    {% endif %}
</body>
</html>